IF OBJECT_ID('Brkr.Task') IS NULL
 CREATE TABLE Brkr.Task(
  TaskId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Task PRIMARY KEY CLUSTERED,
  TaskTypeId TINYINT NOT NULL CONSTRAINT FK_Task_TaskType FOREIGN KEY REFERENCES Brkr.TaskType(TaskTypeId),
  RecordId INT NOT NULL,
  ScheduledDateTime DATETIME2(3) NOT NULL,
  ProcessedDateTime DATETIME2(3) NOT NULL,
  IsCancelled BIT NOT NULL CONSTRAINT DF_Task_IsCancelled DEFAULT(0),
  WasSuccessfull BIT NULL
  )
GO